import html


def _e(value):
    return html.escape(str(value if value is not None else ""), quote=True)


def render_mini_panel(*, panel_token, bot, view, date_from, date_to, summary, groups, recent):
    cl, cu = int(getattr(bot, "cfe_limit", 0) or 0), int(getattr(bot, "cfe_used", 0) or 0)
    rl, ru = int(getattr(bot, "renapo_limit", 0) or 0), int(getattr(bot, "renapo_used", 0) or 0)
    ca, ra = ("∞" if cl == 0 else max(0, cl-cu)), ("∞" if rl == 0 else max(0, rl-ru))
    rows = []
    for g in groups:
        blocked = bool(getattr(g, "is_blocked", False))
        rows.append(
            f'<tr><td><strong>{_e(getattr(g,"custom_name",None) or "Sin nombre")}</strong></td><td class="mono">{_e(g.group_jid)}</td>'
            f'<td><span class="badge {"badge-danger" if blocked else "badge-success"}">{"BLOQUEADO" if blocked else "ACTIVO"}</span></td>'
            f'<td>{getattr(g,"cfe_used",0)}/{getattr(g,"cfe_limit",0) or "∞"}</td><td>{getattr(g,"renapo_used",0)}/{getattr(g,"renapo_limit",0) or "∞"}</td>'
            f'<td><form method="post" action="/botpanel/{_e(panel_token)}/group/{_e(g.group_jid)}/rename" class="inline"><input name="custom_name" value="{_e(getattr(g,"custom_name",None) or "")}" placeholder="Nombre"><button class="btn btn-primary">Guardar</button></form></td>'
            f'<td><form method="post" action="/botpanel/{_e(panel_token)}/group/{_e(g.group_jid)}/toggle"><button class="btn {"btn-success" if blocked else "btn-danger"}">{"Desbloquear" if blocked else "Bloquear"}</button></form></td>'
            f'<td><form method="post" action="/botpanel/{_e(panel_token)}/group/{_e(g.group_jid)}/hide"><button class="btn btn-light">Ocultar</button></form></td></tr>'
        )
    recent_rows = ''.join(f'<tr><td>{_e(r.get("module"))}</td><td class="mono">{_e(r.get("identifier"))}</td><td>{_e(r.get("status"))}</td><td class="mono">{_e(r.get("group_jid"))}</td><td>{_e(r.get("created_at"))}</td><td>{_e(r.get("error"))}</td></tr>' for r in recent)
    title = _e(getattr(bot, "display_name", "Bot")); blocked = bool(getattr(bot, "is_blocked", False))
    css = r''':root{--bg:#f4f6f8;--text:#1f2937;--muted:#6b7280;--line:#e5e7eb;--primary:#334155;--success:#166534;--danger:#991b1b;--shadow:0 8px 24px rgba(15,23,42,.07)}*{box-sizing:border-box}body{margin:0;background:var(--bg);font-family:Arial,sans-serif;color:var(--text)}.wrap{max-width:1400px;margin:auto;padding:16px}.hero{background:linear-gradient(135deg,#1f2937,#334155 55%,#475569);color:#fff;border-radius:24px;padding:22px;box-shadow:var(--shadow);margin-bottom:18px}.hero-top{display:flex;justify-content:space-between;gap:16px;flex-wrap:wrap}.hero h1{margin:0 0 6px}.toolbar{display:flex;gap:10px;flex-wrap:wrap;margin-top:16px}.tool-link{text-decoration:none;padding:10px 16px;border-radius:12px;background:rgba(255,255,255,.10);color:#fff;font-weight:700;border:1px solid rgba(255,255,255,.14)}.cards{display:grid;grid-template-columns:repeat(5,1fr);gap:12px;margin-bottom:16px}.card,.box,.wallet{background:#fff;border:1px solid var(--line);border-radius:18px;box-shadow:var(--shadow)}.card{padding:16px}.label{color:var(--muted);font-size:.85rem;font-weight:800;text-transform:uppercase;margin-bottom:8px}.value{font-size:1.9rem;font-weight:900}.box{overflow:hidden;margin-bottom:16px}.head{padding:16px 18px;background:#fafbfc;border-bottom:1px solid var(--line);display:flex;justify-content:space-between;align-items:center;gap:10px;flex-wrap:wrap}.content{padding:16px}.wallet-grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}.wallet{padding:16px;background:#f8fafc}.wallet-title{font-weight:900;margin-bottom:12px}.wallet-values{display:grid;grid-template-columns:repeat(3,1fr);gap:8px}.wallet-number{background:#fff;border:1px solid var(--line);border-radius:12px;padding:12px}.wallet-number span{display:block;color:var(--muted);font-size:.75rem;font-weight:800}.wallet-number strong{font-size:1.25rem}.table-wrap{overflow-x:auto}table{width:100%;border-collapse:collapse;min-width:1050px}th,td{padding:12px;border-bottom:1px solid var(--line);text-align:left;vertical-align:top}th{background:#1f2937;color:#fff}.btn{border:0;border-radius:12px;padding:10px 14px;font-weight:800;cursor:pointer;text-decoration:none;display:inline-flex}.btn-primary{background:var(--primary);color:#fff}.btn-success{background:var(--success);color:#fff}.btn-danger{background:var(--danger);color:#fff}.btn-light{background:#e5e7eb;color:#111827}.badge{display:inline-flex;padding:4px 10px;border-radius:999px;font-size:12px;font-weight:800}.badge-success{background:#dcfce7;color:#166534}.badge-danger{background:#fee2e2;color:#991b1b}.inline{display:flex;gap:6px}input{padding:10px 12px;border:1px solid #d1d5db;border-radius:12px;font:inherit}.mono{font-family:Consolas,monospace}.small{color:var(--muted);font-size:.84rem}@media(max-width:900px){.cards{grid-template-columns:repeat(2,1fr)}.wallet-grid{grid-template-columns:1fr}}@media(max-width:600px){.cards,.wallet-values{grid-template-columns:1fr}}'''
    return f'''<!doctype html><html lang="es"><head><meta charset="utf-8"><title>Mini Panel {title}</title><meta name="viewport" content="width=device-width,initial-scale=1"><style>{css}</style></head><body><div class="wrap"><section class="hero"><div class="hero-top"><div><h1>Mini Panel · {title}</h1><div>Gestión independiente de grupos, bolsas y entregas CFE/RENAPO.</div></div><span class="badge {'badge-danger' if blocked else 'badge-success'}">{'BOT BLOQUEADO' if blocked else 'BOT PRENDIDO'}</span></div><div class="toolbar"><a class="tool-link" href="/botpanel/{_e(panel_token)}">Hoy</a><a class="tool-link" href="/botpanel/{_e(panel_token)}?view=30d">30 días</a><a class="tool-link" href="/botpanel/{_e(panel_token)}?view=month">Mes actual</a><a class="tool-link" href="/botpanel/{_e(panel_token)}?view=prev_month">Mes anterior</a></div></section>
<div class="cards"><div class="card"><div class="label">Entregadas</div><div class="value">{summary.get('done',0)}</div></div><div class="card"><div class="label">CFE</div><div class="value">{summary.get('cfe_done',0)}</div></div><div class="card"><div class="label">RENAPO</div><div class="value">{summary.get('renapo_done',0)}</div></div><div class="card"><div class="label">Pendientes</div><div class="value">{summary.get('pending',0)}</div></div><div class="card"><div class="label">Errores</div><div class="value">{summary.get('errors',0)}</div></div></div>
<section class="box"><div class="head"><strong>Bolsas y control del bot</strong><form method="post" action="/botpanel/{_e(panel_token)}/bot/toggle"><button class="btn {'btn-success' if blocked else 'btn-danger'}">{'Desbloquear bot' if blocked else 'Bloquear bot'}</button></form></div><div class="content"><div class="wallet-grid"><div class="wallet"><div class="wallet-title">Bolsa CFE</div><div class="wallet-values"><div class="wallet-number"><span>Límite</span><strong>{cl or '∞'}</strong></div><div class="wallet-number"><span>Usados</span><strong>{cu}</strong></div><div class="wallet-number"><span>Disponibles</span><strong>{ca}</strong></div></div><form method="post" action="/botpanel/{_e(panel_token)}/recharge/CFE" class="inline" style="margin-top:12px"><input name="amount" type="number" min="1" placeholder="Recarga"><button class="btn btn-success">Recargar</button></form></div><div class="wallet"><div class="wallet-title">Bolsa RENAPO</div><div class="wallet-values"><div class="wallet-number"><span>Límite</span><strong>{rl or '∞'}</strong></div><div class="wallet-number"><span>Usados</span><strong>{ru}</strong></div><div class="wallet-number"><span>Disponibles</span><strong>{ra}</strong></div></div><form method="post" action="/botpanel/{_e(panel_token)}/recharge/RENAPO" class="inline" style="margin-top:12px"><input name="amount" type="number" min="1" placeholder="Recarga"><button class="btn btn-success">Recargar</button></form></div></div></div></section>
<section class="box"><div class="head"><strong>Agregar grupo</strong></div><div class="content"><form method="post" action="/botpanel/{_e(panel_token)}/group/add" class="inline"><input name="group_jid" placeholder="120363...@g.us" required><input name="custom_name" placeholder="Nombre del grupo"><button class="btn btn-primary">Agregar</button></form></div></section>
<section class="box"><div class="head"><strong>Grupos administrados</strong><span class="small">{len(groups)} grupos</span></div><div class="table-wrap"><table><thead><tr><th>Nombre</th><th>JID</th><th>Estado</th><th>CFE</th><th>RENAPO</th><th>Renombrar</th><th>Bloqueo</th><th>Ocultar</th></tr></thead><tbody>{''.join(rows) or '<tr><td colspan="8">Sin grupos.</td></tr>'}</tbody></table></div></section>
<section class="box"><div class="head"><strong>Historial y evidencias</strong></div><div class="table-wrap"><table><thead><tr><th>Módulo</th><th>Dato</th><th>Estado</th><th>Grupo</th><th>Fecha</th><th>Error</th></tr></thead><tbody>{recent_rows or '<tr><td colspan="6">Sin movimientos.</td></tr>'}</tbody></table></div></section></div></body></html>'''
